name: Coverage

on:
  push:
    branches: [ main, master ]
  schedule:
    # Run coverage weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies with coverage tools
      run: |
        uv sync --dev
        uv add --dev coverage[toml] pytest-cov

    - name: Run tests with coverage
      run: |
        uv run pytest tests/ \
          --cov=pymotivaxmc2 \
          --cov-report=html \
          --cov-report=xml \
          --cov-report=term-missing \
          --disable-warnings \
          -v
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      if: github.event_name == 'push'
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30

    - name: Coverage comment
      if: github.event_name == 'pull_request'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 60 