name: Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install linting dependencies
      run: |
        uv sync --dev
        uv add --dev ruff mypy

    - name: Run ruff linter (non-blocking)
      run: |
        uv run ruff check pymotivaxmc2/ tests/ --output-format=github
      continue-on-error: true

    - name: Run ruff formatter check
      run: |
        uv run ruff format --check pymotivaxmc2/ tests/
      continue-on-error: true

    - name: Run mypy type checker (non-blocking)
      run: |
        uv run mypy pymotivaxmc2/
      continue-on-error: true 